name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Atualizar código
        run: |
          cd ~/matia/frontend
          git reset --hard
          git pull origin main

      - name: Rebuild e restart do frontend
        run: |
          cd ~/matia
          docker compose up -d --build frontend

      - name: Limpar imagens antigas
        run: docker image prune -f